version: 2

aliases:
  - &docker
    - image: circleci/openjdk:8-jdk-node-browsers

  - &environment
    TZ: /usr/share/zoneinfo/America/Los_Angeles

  - &restore_yarn_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-node-{{ arch }}-{{ .Branch }}-
        - v1-node-{{ arch }}-
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

  - &attach_workspace
    at: build

jobs:
  setup:
    docker: *docker
    environment: *environment

    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - *restore_yarn_cache
      - *run_yarn
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build:
    docker: *docker
    environment: *environment

    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run:
          name: Pre-release build
          command: yarn run prerelease

workflows:
  version: 2
  commit:
    jobs:
      - setup
      - build:
          requires:
            - setup
